### ISSUE TITLE
[FEAT] 프로젝트 기본 설정 구성

### ISSUE THREAD

**Issue by cobocho** [makevook/vook-client#1]
# Feature

프로젝트를 위한 Next.js 및 관련 패키지를 설치합니다.

# Todo List

- [x] 모노레포 기반으로 프로젝트를 설치합니다.
- [x] `eslint` 및 `prettier`를 설정합니다.
- [x] 폴더 구조를 정립합니다.
- [x] 프로젝트 관련 패키지를 설정합니다.

# Additional Comment

# References
- [Triple-config-kit 스타일 가이드](https://github.com/titicacadev/triple-config-kit/blob/main/STYLE_GUIDE.md)
