### ISSUE TITLE
[FEAT] staging 환경 배포 구성

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-client#4]
# Feature

비개발자의 리뷰와 데모를 위한 staging 환경 배포 구성

# Todo List

- [x] 배포를 위한 Dockerfile 작성
- [x] CI/CD 스크립트 작성 (w/ dagger)
- [x] Workflow yaml 작성
