### ISSUE TITLE
[FEAT] 디자인 시스템 컴포넌트를 구현한다

### ISSUE THREAD

**Issue by cobocho** [makevook/vook-client#7]
# Feature

피그마에 구현된 디자인 시스템을 기반으로 공통 컴포넌트를 구현합니다.

# Todo List

- [x] 디자인 토큰 추출하기
- [x] 추출한 디자인 토큰 기반으로 `sprinkles` 구축하기
- [x] 공통 컴포넌트 구현하기

# Additional Comment

# References
