### ISSUE TITLE
[FEAT] 용어 검색 MVP 구현한다.

### ISSUE THREAD

**Issue by hin6150** [makevook/vook-client#9]
# Feature

용어 검색 PRD에 맞춰 검색(Search), 용어리스트(Term_list) 기능 구현합니다.

# Todo List

- [x] React-Query를 이용한 RestAPI 연동
- [x] 기본 UI 구성
- [x] 접속한 브라우저 정보에 따른 버튼 표기
- [x] 로컬 스토리지를 이용해 검색 기록 저장
- [x] (Optional) Zustand 초기 환경 설정

# Additional Comment

# References
